import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
const text=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
const bytes=p=>fs.readFileSync(new URL('../'+p,import.meta.url));
const sha=p=>crypto.createHash('sha256').update(bytes(p)).digest('hex');
const schema=text('src/core/schema.js');
const wrapper=text('src/game-terrain/terrain-workbench.js');
const renderer=text('src/game-terrain/terrain-renderer-v6.js');
const surface=text('src/game-terrain/terrain-surface-generator.js');
const app=text('src/app.js');
const html=text('index.html');
const map=JSON.parse(text('assets/game-terrain/worldforge_curated_battlefield.json'));
const manifest=JSON.parse(text('assets/game-terrain/runtime-sync-manifest.json'));
assert.match(schema,/WORLDFORGE_VERSION = '0\.13\.27'/);
assert.match(schema,/gameTerrainWorkbench: '0\.7\.0'/);
assert.match(wrapper,/GAME_TERRAIN_WORKBENCH_VERSION='0\.7\.0'/);
assert.match(wrapper,/EXPERIMENTAL_TERRAIN_RENDERER_VERSION='0\.6\.0'/);
assert.match(wrapper,/TerrainRendererV6/);
assert.match(renderer,/paletteDetail\(/,'PBR V6 must separate RTS palette from photographic micro-detail');
assert.match(renderer,/nearDetail=1\.0-smoothstep\(80\.0,260\.0,dist\)/,'micro-detail must fade at RTS overview distance');
assert.match(renderer,/depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2,polygonOffsetUnits:-2/,'road overlays must avoid mobile z-fighting');
assert.match(renderer,/makeStripGeometry\(pts,\(road\.width\?\?8\)\+2\.2,this\.terrain,\.10\)/,'roads must have a stable positive terrain offset');
assert.match(renderer,/#include <tonemapping_fragment>/);
assert.match(renderer,/#include <colorspace_fragment>/);
assert.deepEqual(map.terrain.visual.rtsPalette,{grass:'#5e784e',dirt:'#7b6549',rock:'#73756e',wet:'#625b50'});
assert.match(surface,/dryBare\*\.28/,'natural dirt breakup must no longer dominate the whole battlefield');
assert.match(wrapper,/strategic \? Math\.min\(max\*\.73,560\)/,'strategic wide camera should use recovery framing');
assert.match(app,/ambient\.intensity=\.68;sun\.intensity=\.76/,'roads/water need readable preview lighting');
assert.ok(map.terrain.visual.roadBlendMeters<=6,'road shoulder blend must stay tight enough to avoid giant mud corridors');
assert.ok(map.terrain.visual.macroVariation>=.08 && map.terrain.visual.macroVariation<=.12,'macro variation should be visible but restrained');
assert.match(html,/PBR V6 · RTS BLEND/);
// Protected ForgeRTS runtime snapshot remains exact.
for(const [p,meta] of Object.entries(manifest.files))assert.equal(sha(p),meta.sha256,`protected runtime snapshot changed: ${p}`);
console.log(JSON.stringify({ok:true,worldforge:'0.13.27',terrainWorkbench:'0.7.0',renderer:'PBR V6 RTS Blend',protectedForgeRTS:true,roadStability:true,distanceAwareDetail:true,paletteSeparation:true},null,2));
