import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const ROOT=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const map=fs.readFileSync(path.join(ROOT,'src/rts-map/rts-map-forge.js'),'utf8');
const app=fs.readFileSync(path.join(ROOT,'src/app.js'),'utf8');
const html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');
const css=fs.readFileSync(path.join(ROOT,'style.css'),'utf8');
const schema=fs.readFileSync(path.join(ROOT,'src/core/schema.js'),'utf8');
assert.match(map,/RTS_MAP_FORGE_VERSION='0\.2\.3'/);
assert.match(map,/worldforge\.rts-map\.v1/);
for(const size of ['512','768','1024','1536'])assert.match(map,new RegExp(size));
for(const feature of ['mountainPasses','valleyWar','hiddenPocket','safeExpansion','mainRoute','flankRoute','centralConnector','navigation','buildable','FogPreview','RTS_MOVEMENT_CLASSES','tracked','wheeled','infantry','amphibious','air','movementMask','slopeDegrees','bridgeData'])assert.match(map,new RegExp(feature));
for(const id of ['rtsMapPanel','mapSeed','mapSize','mapPlayers','mapBiome','mapTacticalProfile','mapRelief','mapForest','mapResources','mapStartProtection','mapGenerate','mapViewOverview','mapViewTop','mapViewStart','mapViewTactical','mapFogPreview','mapShowZones','mapMovementPreview','mapTacticalScore','mapExportRecipe','mapExportMeta','mapExportGLB','mapMinimap'])assert.match(html,new RegExp(`id="${id}"`));
assert.match(html,/Terrain only:/);
assert.match(html,/not prebuilt faction bases/);
assert.match(app,/RTSMapForge/);
assert.match(app,/activateRTSMapMode/);
assert.match(app,/generateRTSMap/);
assert.match(app,/jumpFromMinimap/);
assert.match(css,/rts-map-mode/);
assert.match(schema,/WORLDFORGE_VERSION = '0\.13\.8'/);
assert.match(schema,/rtsMapForge: '0\.2\.3'/);
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(x=>x[1]);
assert.equal(new Set(ids).size,ids.length,'duplicate DOM ids');
const refs=[...app.matchAll(/\$\('([^']+)'\)/g)].map(x=>x[1]);
const missing=[...new Set(refs.filter(x=>!ids.includes(x)))];
assert.deepEqual(missing,[],'app references missing DOM ids');
console.log(JSON.stringify({ok:true,rtsMapForge:'0.2.3',mapSizes:[512,768,1024,1536],tacticalProfiles:3,terrainOnly:true,navGrid:true,fogPreview:true,minimap:true},null,2));
