import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const ROOT=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const map=fs.readFileSync(path.join(ROOT,'src/rts-map/rts-map-forge.js'),'utf8');
const app=fs.readFileSync(path.join(ROOT,'src/app.js'),'utf8');
const html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');

assert.match(map,/RTS_MAP_FORGE_VERSION='0\.2\.4'/);
for(const key of ['tracked','wheeled','infantry','amphibious','air']) assert.match(map,new RegExp(`${key}:\\{bit:`));
assert.match(map,/maxSlopeDeg:32/,'tracked slope profile missing');
assert.match(map,/maxSlopeDeg:22/,'wheeled slope profile missing');
assert.match(map,/maxSlopeDeg:42/,'infantry slope profile missing');
assert.match(map,/waterCost:1\.18/,'amphibious water profile missing');
assert.match(map,/airCost:1\.00/,'air profile missing');
assert.match(map,/trunkGeo\.rotateX\(Math\.PI\/2\)/,'tree trunks are not converted Y-up -> Z-up');
assert.match(map,/crownGeo\.rotateX\(Math\.PI\/2\)/,'tree crowns are not converted Y-up -> Z-up');
assert.match(map,/_bridgeFrame\(/,'bank-sampled bridge framing missing');
assert.match(map,/Approach_A/,'bridge approach A missing');
assert.match(map,/Approach_B/,'bridge approach B missing');
assert.match(map,/clearance:/,'bridge clearance metadata missing');
assert.match(map,/endpoints:/,'bridge traversal endpoints missing');
assert.match(map,/movementMask/,'movement bitmask export missing');
assert.match(map,/slopeDegrees/,'slope export missing');
assert.match(map,/costScale:10/,'compact class movement costs missing');
assert.match(map,/reachableStartPercent/,'per-class connectivity audit missing');
assert.match(map,/setMovementPreview/,'movement preview method missing');
assert.match(app,/mapMovementPreview/,'movement preview UI wiring missing');
assert.match(html,/id="mapMovementPreview"/,'movement preview selector missing');
console.log(JSON.stringify({ok:true,rtsMapForge:'0.2.4',movementClasses:5,uprightFoliage:true,gradedBridges:true,classCosts:true,classConnectivity:true},null,2));
