import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const lib=fs.readFileSync(path.join(root,'src/rts/rts-asset-library.js'),'utf8');
const forge=fs.readFileSync(path.join(root,'src/building/building-forge.js'),'utf8');
const skirmish=fs.readFileSync(path.join(root,'src/rts/skirmish-test.js'),'utf8');
const defs=fs.readFileSync(path.join(root,'src/rts/data/rts-definitions.js'),'utf8');
const app=fs.readFileSync(path.join(root,'src/app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
for(const rel of ['assets/buildings/aegis_command_nexus_hq_v13.glb','assets/buildings/aegis_grid_bastion_power_plant_v1.glb'])assert.ok(fs.statSync(path.join(root,rel)).size>10000,`${rel} missing/too small`);
assert.match(lib,/commandNexus/);assert.match(lib,/gridBastion/);assert.match(lib,/WF_TEAM_PRIMARY/);assert.match(lib,/FACTION_PALETTES/);
assert.match(forge,/BUILDING_FORGE_VERSION='0\.1\.0'/);assert.match(forge,/instantiateMasterBuilding/);
assert.match(defs,/masterAsset:'commandNexus'/);assert.match(defs,/masterAsset:'gridBastion'/);
assert.match(skirmish,/instantiateMasterBuilding/);assert.match(skirmish,/masterBuildingForRole/);assert.match(skirmish,/loadAegisReferenceVehicle/);assert.match(skirmish,/spawnSupportUnit/);assert.match(skirmish,/SKIRMISH_VERSION='0\.3\.0'/);
assert.match(app,/activateRTSBuildingMode/);assert.match(app,/rtsBuildingExportGLB/);assert.match(app,/skirmishSpawnHmmwv/);assert.match(html,/data-mode="rtsbuilding"/);assert.match(html,/BUILDING FORGE 0\.1/);assert.match(html,/id="skirmishSpawnHmmwv"/);assert.match(html,/id="skirmishSpawnTalon"/);
console.log(JSON.stringify({ok:true,masterBuildings:2,palettes:5,skirmishMasterReplacement:true,referenceVehicleDepot:true}));
