import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const ROOT=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const gen=fs.readFileSync(path.join(ROOT,'src/vehicle/vehicle-generator.js'),'utf8');
const app=fs.readFileSync(path.join(ROOT,'src/app.js'),'utf8');
const html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');
const schema=fs.readFileSync(path.join(ROOT,'src/core/schema.js'),'utf8');
assert.match(gen,/VEHICLE_GENERATOR_VERSION='0\.3\.0'/);
for(const key of ['mbt','hmmwv50','attackHeli','lightTank','apc','ifv','mrap','spg','mlrs','sam','spaag','recon','truck'])assert.match(gen,new RegExp(`\\b${key}:\\{`));
for(const shape of ['wedge','heavy','compact'])assert.match(gen,new RegExp(`\\b${shape}:\\{label:`));
for(const node of ['VehicleRoot','HullRoot','TurretSocket','TurretRoot','GunPitchRoot','RWSRoot','RWSGunPitchRoot','MuzzleSocket','SmokeLeftSocket','SmokeRightSocket','EngineEffectSocket'])assert.match(gen,new RegExp(`['"]${node}['"]`));
for(const detail of ['TurretShell','TurretCheek','ThermalSleeve','BoreEvacuator','SideSkirt','RoadWheel','APS_Radar','CommanderPanoramicSight'])assert.match(gen,new RegExp(detail));
assert.match(gen,/facetedBodyGeometry/);
assert.match(gen,/quality:type==='mbt'\?'aegis-grade'/);
assert.match(gen,/flatShading:true/);
assert.match(app,/generateLowPolyVehicle/);
assert.match(app,/loadAegisReferenceVehicle/);
assert.match(app,/installGeneratedYUp/);
assert.match(app,/vehicleSilhouette/);
assert.match(app,/vehicleDetail/);
assert.match(app,/vehicleRoadWheels/);
assert.match(html,/VEHICLE FORGE 0\.3 · AEGIS REFERENCE FAMILIES/);
assert.match(html,/Aegis HMMWV-50 · Reference Grade/);
assert.match(html,/Aegis Talon AH-X · Reference Grade/);
for(const id of ['vehicleSilhouette','vehicleDetail','vehicleRoadWheels'])assert.match(html,new RegExp(`id="${id}"`));
assert.match(schema,/WORLDFORGE_VERSION = '0\.9\.8'/);
assert.match(schema,/vehicleGenerator: '0\.3\.0'/);
console.log(JSON.stringify({ok:true,vehicleGenerator:'0.3.0',families:13,mbtSilhouettes:3,styles:3,palettes:4,functionalHierarchy:true},null,2));
